### PR TITLE
Setup CI to check for broken links

### PR DESCRIPTION
**Pull request by CreepySkeleton**
Based on [this example](https://github.com/richelbilderbeek/travis_markdown-link-check)

### CODE REVIEW

**Comment by CreepySkeleton** [comment]
Well it was about "./check_dead_links" not having permission to execute

**Comment by CreepySkeleton** [comment]
@dtolnay you may also want to set [a travis cron job](https://docs.travis-ci.com/user/cron-jobs/)

**Review by dtolnay — COMMENTED** [review]
Thanks! It looks like this didn't run anything though?

check

I added a simpler implementation in https://github.com/dtolnay/rust-faq/commit/49de8ea49cede8cb35b57e17d50a589323452470 and I would welcome PRs to fix the existing broken links. https://travis-ci.com/dtolnay/rust-faq/builds/133079355

**Comment by CreepySkeleton** [comment]
@dtolnay Every one of those "crates.io/*" links work in my web-browser just fine. Maybe this failure is because of the script crawles the links too frequently? crates.io seems to have [one per second request](https://crates.io/policies#crawlers) limitation. Any thoughts?

https://doc.rust-lang.org/book/ch07-00-packages-crates-and-modules.html is indeed broken though.

**Comment by dtolnay** [comment]
#7 should help.

**Pull request closed without merging**
